
server.forward-headers-strategy: framework
management:
    zipkin:
        tracing:
            endpoint: http://${ZIPKIN_HOST:zipkin}:${ZIPKIN_PORT:9411}/api/v2/spans
eureka:
    instance:
        hostname: ${DISCOVERY_INSTANCE_HOST:event-service}
