server:
  port: 8060

eureka:
  client:
    serviceUrl:
        defaultZone: http://${DISCOVERY_SERVICE_HOST:discovery-service}:${DISCOVERY_SERVICE_PORT:8761}/eureka/

logging:
    level:
        root: ${LOG_LEVEL_ROOT:info}
        com:
            github:
                manosbatsis: debug
        org.springframework:
            cloud: debug
    pattern: "%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  application:
        name: gateway-service
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          - id: user-service
            uri: lb://user-service
            predicates:
                - Path=/user/**
            filters:
                - RewritePath=/userservice/(?<path>.*), /$\{path}
          - id: event-service
            uri: lb://event-service
            predicates:
                - Path=/event/**
            filters:
                - RewritePath=/event/(?<path>.*), /$\{path}
          - id: openapi
            uri: http://localhost:${server.port}
            predicates:
                - Path=/v3/api-docs/**
            filters:
                - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: event
        url: /v3/api-docs/event

management:
  tracing:
    sampling:
      probability: 1.0
