server:
    port: 9080

spring:
    application:
        name: user-service
    config:
        import: "optional:configserver:http://${CONFIG_SERVICE_HOST:config-service}:${CONFIG_SERVICE_PORT:8088}"
