spring:
    config:
        import: "optional:configserver:http://config-service:8088"
        activate:
            on-profile: docker
---
server:
    port: 8761

spring:
    application:
        name: discovery-service
    config:
        import: "optional:configserver:http://localhost:8088"
