server:
    port: 9082

spring:
    application:
        name: email-service
    config:
        import: "optional:configserver:http://${CONFIG_SERVICE_HOST:config-service}:${CONFIG_SERVICE_PORT:8088}"
