server:
    port: 9081

spring:
    application:
        name: event-service
    config:
        import: "optional:configserver:http://${CONFIG_SERVICE_HOST:config-service}:${CONFIG_SERVICE_PORT:8088}"
